name: "sphinx"
mode: "dev"
port: 8084
version: "v0.0.1"
start_time: "2025-04-09"
machine_code: "1744168604"

auth:
  jwt_expire: 3600

log:
  level: "debug"
  filename: "runtime/logs/sphinx.log"
  max_size: 1
  max_age: 30
  max_backups: 7
mysql:
  host: 127.0.0.1
  port: 3306
  user: "root"
  password: "123456"
  dbname: "sphinx"
  max_open_conns: 200
  max_idle_conns: 50
redis:
  host: 127.0.0.1
  port: 6379
  password: "123456"
  db: 0
  pool_size: 100